config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               sessions: 'users/sessions'
             },
             skip: [:registrations]

  resources :cycle_counts do
    resources :pallets
  end

  resources :locations

  namespace :admin do
    resources :users
  end

  root 'site/home#index'
end

app/models/cycle_count.rb
class CycleCount < ActiveRecord::Base
  belongs_to :location
  belongs_to :created_by, class_name: 'User', foreign_key: :creator_id
  belongs_to :updated_by, class_name: 'User', foreign_key: :updater_id
  has_many :pallets

  validates :location_id, :requested_date, presence: true
  validates :location_id, numericality: true
  validates :location_id, uniqueness: { scope: :requested_date }
end

app/controllers/cycle_counts_controller.rb
class CycleCountsController < ApplicationController
  include BasicCRUDHandler
  before_action -> { authorize :cycle_count }
  respond_to :html

  def index
    render_index
  end

  def show
    render_show
  end

  def new
    render_new
  end

  def edit
    render_edit
  end

  def destroy
    if cycle_count.destroy
      redirect_to cycle_counts_path, notice: t('.success')
    else
      redirect_to cycle_counts_path, alert: t('.failure')
    end
  end

  private

  def render_index
    render :index, locals: { cycle_counts: cycle_counts }
  end

  def render_show
    render :show, locals: { cycle_count: cycle_count }
  end

  def render_new
    render :new, locals: { resource: cycle_count }
  end

  def render_edit
    render :edit, locals: { resource: cycle_count }
  end

  def cycle_count_params
    return {} if params[:cycle_count].nil?

    params
      .require(:cycle_count)
      .permit(:location_id, :requested_date)
  end

  def cycle_count
    @cycle_count ||= params[:id] ? find_cycle_count : build_cycle_count
    @cycle_count.decorate
  end

  def cycle_counts
    @cycle_counts ||= CycleCount.all.page(params[:page])
    @cycle_counts = PaginatingDecorator.decorate(@cycle_counts)
  end

  def build_cycle_count
    CycleCount.new(cycle_count_params)
  end

  def find_cycle_count
    CycleCount.find(params[:id])
  end
end

app/views/cycle_counts/_cycle_count.html.erb
<tr>
  <td><%= cycle_count.location.description %></td>
  <td><%= cycle_count.formatted_requested_date %></td>
  <td><%= cycle_count.pallets.count %></td>
  <td><%= link_to 'Show', cycle_count_path(cycle_count) %></td>
  <td><%= link_to 'Edit', edit_cycle_count_path(cycle_count) %></td>
  <td><%= link_to 'Destroy', cycle_count, method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/cycle_counts/_form.html.erb
<div class="form-inputs">
  <%= error_messages model %>

  <%= f.association :location,
                    collection: Location.all,
                    label_method: :description,
                    value_method: :id,
                    prompt: 'Choose a Location' %>
  <%= f.input :requested_date, as: :date, html5: true %>
</div>

app/views/cycle_counts/_pallet.html.erb
<tr>
  <td><%= pallet.pallet_number %></td>
  <td><%= pallet.notes %></td>
  <td><%= pallet.check_state %></td>
  <td><%= pallet.check_location %></td>
  <td><%= pallet.check_result %></td>
  <td><%= link_to '',
                  edit_cycle_count_pallet_path(pallet.cycle_count_id, pallet),
                  class: 'btn btn-default btn-sm glyphicon glyphicon-pencil' %>
</tr>

app/views/cycle_counts/edit.html.erb
<%= render layout: '/header',
           locals: { header: 'h2', title: t('.title') } do %>
  <nav class="pull-right">
    <%= link_to 'Return to Cycle Counts',
                cycle_counts_path,
                class: 'btn btn-link' %>
  </nav>
<% end %>

<%= simple_form_for(resource, method: :patch, url: cycle_count_path(resource)) do |f| %>
  <%= render partial: 'form', locals: { f: f, model: resource } %>
  <div class="form-actions">
    <%= f.button :submit, t('.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/cycle_counts/index.html.erb
<%= link_to 'Create Cycle Count', new_cycle_count_path(), class: 'btn btn-warning' %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Location Description</th>
      <th>Requested Date</th>
      <th>Pallet Count</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render @cycle_counts %>
  </tbody>
</table>
<%= paginate @cycle_counts %>

app/views/cycle_counts/new.html.erb
<%= render layout: '/header',
           locals: { header: 'h2', title: t('.title') } do %>
  <nav class="pull-right">
    <%= link_to 'Return to Cycle Counts',
                cycle_counts_path,
                class: 'btn btn-link' %>
  </nav>
<% end %>

<%= simple_form_for(resource, method: :post, url: cycle_counts_path) do |f| %>
  <%= render partial: 'form', locals: { f: f, model: resource } %>
  <div class="form-actions">
    <%= f.button :submit, t('.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/cycle_counts/show.html.erb
<%= render layout: '/header',
           locals: { header: 'h2', title: 'Cycle Count' } do %>
  <nav class="pull-right">
    <%= link_to 'Add Pallet',
                new_cycle_count_pallet_path(cycle_count),
                class: 'btn btn-link' %>
    <%= link_to 'Edit',
                edit_cycle_count_path(cycle_count),
                class: 'btn btn-link' %>
    <%= link_to 'Return to Cycle Counts',
                cycle_counts_path,
                class: 'btn btn-link' %>
  </nav>
<% end %>
<div class="form form-horizontal">
  <div class="form-group">
    <label class="col-sm-3 control-label">Location Description</label>
    <p class="col-sm-6 form-control-static">
      <%= cycle_count.location.description %>
    </p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Requested Date</label>
    <p class="col-sm-6 form-control-static">
      <%= cycle_count.formatted_requested_date %>
    </p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Created By</label>
    <p class="col-sm-6 form-control-static">
      <%= cycle_count.created_by.email %>
    </p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Created At</label>
    <p class="col-sm-6 form-control-static">
      <%= cycle_count.formatted_created_at %>
    </p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Updated By</label>
    <p class="col-sm-6 form-control-static">
      <%= cycle_count.updated_by.email %>
    </p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Updated At</label>
    <p class="col-sm-6 form-control-static">
      <%= cycle_count.formatted_updated_at %>
    </p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Pallet Count</label>
    <p class="col-sm-6 form-control-static">
      <%= cycle_count.pallets.count %>
    </p>
  </div>
</div>
<br />
<% unless cycle_count.pallets.count == 0 %>
  <table class="table table-striped table-bordered">
    <thead>
      <th>Pallet Number</th>
      <th>Notes</th>
      <th>Current State</th>
      <th>Grossman Location</th>
      <th>Result</th>
      <th></th>
    </thead>
    <tbody>
      <%= render partial: "pallet", collection: cycle_count.pallets %>
    </tbody>
  </table>
<% end %>