config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               sessions: 'users/sessions'
             },
             skip: [:registrations]

  resources :cycle_counts do
    resources :pallets
  end

  resources :locations

  namespace :admin do
    resources :users
  end

  root 'site/home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :invitable,
         :recoverable,
         :rememberable,
         :trackable

  model_stamper

  ROLE_NAMES = %w(
    admin
    moderator
    cycle_counter
  ).freeze

  validates :email, :name, :role_name, presence: true
  validates :email, uniqueness: true, case_sensitive: false

  def after_password_reset; end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action -> { authorize :user }
    respond_to :html

    def index
      render_index
    end

    def show
      render_show
    end

    def new
      render_new
    end

    def create
      if user.save
        redirect_to admin_user_path(user),
                    notice: t('.success')
      else
        flash[:alert] = t('.failure')
        render_new
      end
    end

    def edit
      render_edit
    end

    def update
      if user.update_attributes(user_params)
        redirect_to admin_user_path(user),
                    notice: t('.success')
      else
        flash[:alert] = t('.failure')
        render_edit
      end
    end

    private

    def render_index
      render :index, locals: { users: users }
    end

    def render_show
      render :show, locals: { user: user }
    end

    def render_new
      render :new, locals: { user: user }
    end

    def render_edit
      render :edit, locals: { user: user }
    end

    def user_params
      return {} if params[:user].nil?

      params
        .require(:user)
        .permit(:email, :name, :is_active, :role_name)
    end

    def user
      @user ||= params[:id] ? find_user : build_user
      @user.decorate
    end

    def users
      @users ||= User.all.page(params[:page])
      @users = PaginatingDecorator.decorate(@users)
    end

    def build_user
      User.new(user_params)
    end

    def find_user
      User.find(params[:id])
    end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    layout 'minimal'
  end
end

app/views/admin/users/_form.html.erb
<div class="form-inputs">
  <%= error_messages model %>

  <%= f.input :email %>
  <%= f.input :name %>
  <%= f.input :role_name,
              label: 'Role',
              collection: (User::ROLE_NAMES),
              prompt: '-Choose a Role Type-' %>
  <%= f.input :is_active, :as => :boolean %>
</div>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.email %></td>
  <td><%= user.name %></td>
  <td><%= user.role_name %></td>
  <td><%= user.active_label %></td>
  <td><%= link_to 'Show', admin_user_path(user) %></td>
  <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
</tr>

app/views/admin/users/edit.html.erb
<%= render layout: '/header',
           locals: { header: 'h2', title: t('.title') } do %>
  <nav class="pull-right">
    <%= link_to 'Return to Users',
                admin_users_path,
                class: 'btn btn-link' %>
  </nav>
<% end %>

<%= simple_form_for(user, method: :patch, url: admin_user_path(user)) do |f| %>
  <%= render partial: 'form', locals: { f: f, model: user } %>
  <div class="form-actions">
    <%= f.button :submit, t('.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<%= link_to 'Create User', new_admin_user_path(), class: 'btn btn-warning' %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Role</th>
      <th>Status</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>
<%= paginate @users %>

app/views/admin/users/new.html.erb
<%= render layout: '/header',
           locals: { header: 'h2', title: t('admin.new.title') } do %>
  <nav class="pull-right">
    <%= link_to 'Return to Users',
                admin_users_path,
                class: 'btn btn-link' %>
  </nav>
<% end %>

<%= simple_form_for(user, method: :post, url: admin_users_path) do |f| %>
  <%= render partial: 'form', locals: { f: f, model: user } %>
  <div class="form-actions">
    <%= f.button :submit, t('admin.new.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/show.html.erb
<%= render layout: '/header',
           locals: { header: 'h2', title: user.name } do %>
  <nav class="pull-right">
    <%= link_to 'Return to Users', admin_users_path, class: 'btn btn-link' %>
    <%= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-link' %>
  </nav>
<% end %>
<div class="form form-horizontal">
  <div class="form-group">
    <label class="col-sm-3 control-label">Name</label>
    <p class="col-sm-6 form-control-static"><%= user.name %></p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Email</label>
    <p class="col-sm-6 form-control-static"><%= user.email %></p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Role</label>
    <p class="col-sm-6 form-control-static"><%= user.role_name %></p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Active?</label>
    <p class="col-sm-6 form-control-static">
      <%= user.active_label %>
    </p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Created At</label>
    <p class="col-sm-6 form-control-static">
      <%= user.formatted_created_at %>
    </p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Updated At</label>
    <p class="col-sm-6 form-control-static">
      <%= user.formatted_updated_at %>
    </p>
  </div>
</div>