config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               sessions: 'users/sessions'
             },
             skip: [:registrations]

  resources :cycle_counts do
    resources :pallets
  end

  resources :locations

  namespace :admin do
    resources :users
  end

  root 'site/home#index'
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :created_by, class_name: 'User', foreign_key: :creator_id
  belongs_to :updated_by, class_name: 'User', foreign_key: :updater_id
  has_many :cycle_counts
  has_many :pallets, through: :cycle_counts

  validates :location_number, :area_number, :sequence_number, :description,
            presence: true
  validates :location_number,
            uniqueness: { scope: [:area_number, :sequence_number] }
  validates :location_number, :area_number, :sequence_number, numericality: true
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  include BasicCRUDHandler
  before_action -> { authorize :location }
  respond_to :html

  def index
    render_index
  end

  def show
    render_show
  end

  def new
    render_new
  end

  def edit
    render_edit
  end

  def destroy
    if location.destroy
      redirect_to locations_path, notice: t('.success')
    else
      redirect_to locations_path, alert: t('.failure')
    end
  end

  private

  def render_index
    render :index, locals: { locations: locations }
  end

  def render_show
    render :show, locals: { location: location }
  end

  def render_new
    render :new, locals: { resource: location }
  end

  def render_edit
    render :edit, locals: { resource: location }
  end

  def location_params
    return {} if params[:location].nil?

    params
      .require(:location)
      .permit(:location_number, :area_number, :sequence_number, :description)
  end

  def location
    @location ||= params[:id] ? find_location : build_location
    @location.decorate
  end

  def locations
    @locations ||= Location.all.page(params[:page])
  end

  def build_location
    Location.new(location_params)
  end

  def find_location
    Location.find(params[:id])
  end
end

app/views/locations/_form.html.erb
<div class="form-inputs">
  <%= error_messages model %>

  <%= f.input :location_number %>
  <%= f.input :area_number %>
  <%= f.input :sequence_number %>
  <%= f.input :description %>
</div>

app/views/locations/_location.html.erb
<tr>
  <td><%= location.location_number %></td>
  <td><%= location.area_number %></td>
  <td><%= location.sequence_number %></td>
  <td><%= location.description %></td>
  <td><%= link_to 'Show', location_path(location) %></td>
  <td><%= link_to 'Edit', edit_location_path(location) %></td>
  <td><%= link_to 'Destroy', location, method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/locations/edit.html.erb
<%= render layout: '/header',
           locals: { header: 'h2', title: t('.title') } do %>
  <nav class="pull-right">
    <%= link_to 'Return to Location',
                locations_path,
                class: 'btn btn-link' %>
  </nav>
<% end %>

<%= simple_form_for(location, method: :patch, url: location_path(location)) do |f| %>
  <%= render partial: 'form', locals: { f: f, model: location } %>
  <div class="form-actions">
    <%= f.button :submit, t('.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/locations/index.html.erb
<%= link_to 'Create Location', new_location_path(), class: 'btn btn-warning' %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Location Number</th>
      <th>Area Number</th>
      <th>Sequence Number</th>
      <th>Description</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render @locations %>
  </tbody>
</table>
<%= paginate @locations %>

app/views/locations/new.html.erb
<%= render layout: '/header',
           locals: { header: 'h2', title: t('.title') } do %>
  <nav class="pull-right">
    <%= link_to 'Return to Locations',
                locations_path,
                class: 'btn btn-link' %>
  </nav>
<% end %>

<%= simple_form_for(resource, method: :post, url: locations_path) do |f| %>
  <%= render partial: 'form', locals: { f: f, model: resource } %>
  <div class="form-actions">
    <%= f.button :submit, t('.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/locations/show.html.erb
<%= render layout: '/header',
           locals: { header: 'h2', title: 'Location' } do %>
  <nav class="pull-right">
    <%= link_to 'Return to Locations', locations_path, class: 'btn btn-link' %>
    <%= link_to 'Edit', edit_location_path(location), class: 'btn btn-link' %>
  </nav>
<% end %>
<div class="form form-horizontal">
  <div class="form-group">
    <label class="col-sm-3 control-label">Location Number</label>
    <p class="col-sm-6 form-control-static"><%= location.location_number %></p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Area Number</label>
    <p class="col-sm-6 form-control-static"><%= location.area_number %></p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Sequence Number</label>
    <p class="col-sm-6 form-control-static"><%= location.sequence_number %></p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Description</label>
    <p class="col-sm-6 form-control-static"><%= location.description %></p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Created By</label>
    <p class="col-sm-6 form-control-static">
      <%= location.created_by.email %>
    </p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Created At</label>
    <p class="col-sm-6 form-control-static">
      <%= location.formatted_created_at %>
    </p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Updated By</label>
    <p class="col-sm-6 form-control-static">
      <%= location.updated_by.email %>
    </p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Updated At</label>
    <p class="col-sm-6 form-control-static">
      <%= location.formatted_updated_at %>
    </p>
  </div>
</div>